name: learn_flutter_aws
description: "A new Flutter project for learning flutter and learning how to connect it to the AWS backend apis"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  # flutter
  bloc: 8.1.4
  flutter_bloc: 8.1.5
  equatable: 2.0.5
  go_router: 14.1.4
  logger: 2.3.0
  flutter_dotenv: 5.1.0
  intl: 0.18.1

  # persistent & data
  graphql: 5.1.3
  graphql_flutter: 5.1.2

  shared_preferences: 2.2.3
  flutter_secure_storage: 9.2.2
  drift: 2.18.0

  # test
  bloc_test: 9.1.7
  mockito: 5.4.4
  mocktail: 1.0.3

  # native
  flutter_native_splash: 2.4.0
  permission_handler: 11.3.1
  flutter_launcher_icons: 0.13.1
  image_picker: 1.1.1
  flutter_displaymode: 0.6.0

  # ui & presentation
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.8

  # integrations
  sentry: 8.2.0
  sentry_flutter: 8.2.0
  amplitude_flutter: 3.16.2
  amazon_cognito_identity_dart_2: 3.6.5

  # others 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    # project config
    - .env
    
    # proeject assets
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/
 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated